// ─────────────────────────────────────────────────────────
// pdfReport.js — pdfmake-based PDF Report Generator
// ─────────────────────────────────────────────────────────

// Color palette
const C = {
    emerald:     [16, 185, 129],
    emeraldHex:  '#10b981',
    navy:        '#1e293b',
    darkText:    '#1e293b',
    grayText:    '#64748b',
    lightGray:   '#f1f5f9',
    white:       '#ffffff',
    red:         '#ef4444',
    redBg:       '#fee2e2',
    greenBg:     '#d1fae5',
    blue:        '#3b82f6',
    amber:       '#f59e0b',
    tableBorder: '#e2e8f0',
    headerBg:    '#10b981',
};

// ASCII-safe arrow/symbol replacements for pdfmake's bundled Roboto subset
const ARR = '->';
const DARR = '=>';
const EPS = 'eps';

const STAGE_DESCRIPTIONS = [
    '',
    'Identifies nullable non-terminals (variables that can derive the empty string). All epsilon-productions are removed, and new alternative productions are generated by substituting nullable symbols.',
    'Computes the derivation closure for each variable and collapses redundant unit indirection (A -> B) by substituting non-unit productions directly.',
    'Prunes symbols that are non-productive (cannot derive a terminal string) or unreachable from the start symbol S.',
    'Runs the entire pipeline a second time on the output to verify mathematical convergence and stability.'
];

// Sanitize any Unicode arrows/symbols from the logic module output
function sanitize(text) {
    if (typeof text !== 'string') return text;
    return text
        .replace(/→/g, ARR)
        .replace(/⟹/g, DARR)
        .replace(/ε/g, EPS)
        .replace(/—/g, '--')
        .replace(/·/g, '-')
        .replace(/✓/g, '[PASS]')
        .replace(/⚠/g, '[WARN]')
        .replace(/✔/g, '[PASS]');
}

// ─── Canvas capture with 2x upscale ────────────────────

function captureNetworkCanvas(networkContainer) {
    try {
        const canvas = networkContainer.querySelector('canvas');
        if (!canvas) return null;

        const scale = 2;
        const w = canvas.width;
        const h = canvas.height;

        const upscaled = document.createElement('canvas');
        upscaled.width = w * scale;
        upscaled.height = h * scale;
        const ctx = upscaled.getContext('2d');

        ctx.fillStyle = '#FFFFFF';
        ctx.fillRect(0, 0, upscaled.width, upscaled.height);
        ctx.scale(scale, scale);
        ctx.drawImage(canvas, 0, 0);

        return upscaled.toDataURL('image/png', 0.92);
    } catch (e) {
        console.warn('Graph capture failed:', e);
        return null;
    }
}

// ─── Grammar formatting helpers ────────────────────────

function grammarToTableBody(grammar) {
    const keys = Object.keys(grammar).sort();
    return keys.map(lhs => {
        const rhs = grammar[lhs].map(p => p === '' ? EPS : p).join('  |  ');
        return [
            { text: lhs, bold: true, fontSize: 9, color: C.navy, noWrap: true },
            { text: ARR, fontSize: 9, color: C.grayText, alignment: 'center', noWrap: true },
            { text: rhs, fontSize: 9, color: C.darkText }
        ];
    });
}

// ─── Compact log extraction ────────────────────────────

function extractLogRows(stage) {
    const logs = stage.step_logs || stage.logs || [];
    const rows = [];

    logs.forEach(log => {
        if (log.type === 'nullable_detection' && log.nullable_symbols?.length > 0) {
            rows.push([
                { text: 'Nullable Set', bold: true, color: C.amber },
                { text: `N = { ${log.nullable_symbols.join(', ')} }`, color: C.darkText }
            ]);
        }

        if (log.type === 'closure_calculation' && log.closure) {
            for (const k in log.closure) {
                rows.push([
                    { text: `Closure D(${k})`, bold: true, color: C.blue },
                    { text: `{ ${log.closure[k].join(', ')} }`, color: C.darkText }
                ]);
            }
        }

        if (log.type === 'production_generation' && log.rule_transformations) {
            log.rule_transformations.forEach(rt => {
                const generated = (rt.generated_rules || []).filter(g => g.type === 'generated');
                generated.forEach(g => {
                    rows.push([
                        { text: 'Generated', bold: true, color: C.emeraldHex },
                        { text: sanitize(`${rt.original_rule}  =>  ${g.rule}`), color: C.darkText }
                    ]);
                });
            });
        }

        if (log.type === 'unit_replacement' && log.rule_transformations) {
            log.rule_transformations.forEach(rt => {
                rt.removed_units?.forEach(ru => {
                    rows.push([
                        { text: 'Removed Unit', bold: true, color: C.red },
                        { text: sanitize(ru), color: C.darkText }
                    ]);
                });
                rt.added_productions?.forEach(ap => {
                    rows.push([
                        { text: 'Substituted', bold: true, color: C.emeraldHex },
                        { text: sanitize(ap.rule), color: C.darkText }
                    ]);
                });
            });
        }

        if (log.type === 'phase1' || log.type === 'phase2') {
            log.removed_symbols?.forEach(sym => {
                rows.push([
                    { text: 'Pruned Symbol', bold: true, color: C.red },
                    { text: sym, color: C.darkText }
                ]);
            });
            log.removed_rules?.forEach(rr => {
                rows.push([
                    { text: 'Removed Rule', bold: true, color: C.red },
                    { text: sanitize(rr.original_rule), color: C.darkText }
                ]);
            });
        }

        if (log.type === 'summary-clear') {
            rows.push([
                { text: '[PASS]', bold: true, color: C.emeraldHex },
                { text: 'Grammar is mathematically stable -- no further reductions possible.', color: C.darkText }
            ]);
        }
        if (log.type === 'summary-warning') {
            rows.push([
                { text: '[WARN]', bold: true, color: C.red },
                { text: 'Grammar required further reductions on validation pass.', color: C.darkText }
            ]);
        }
    });

    return rows;
}

// ─── Sets display ──────────────────────────────────────

function buildSetsContent(stage, stageIdx) {
    const sets = stage.stage_sets || stage.sets || {};
    const items = [];

    if (stageIdx === 1 && sets.nullable) {
        items.push({
            text: [
                { text: 'Nullable Set  N = ', bold: true, color: C.navy, fontSize: 9 },
                { text: `{ ${sets.nullable.join(', ') || 'empty'} }`, color: C.emeraldHex, fontSize: 9 }
            ],
            margin: [0, 1, 0, 1]
        });
    }

    if (stageIdx === 2 && sets.closures) {
        for (const k in sets.closures) {
            items.push({
                text: [
                    { text: `D(${k}) = `, bold: true, color: C.navy, fontSize: 8 },
                    { text: `{ ${sets.closures[k].join(', ')} }`, color: C.blue, fontSize: 8 }
                ],
                margin: [10, 0, 0, 0]
            });
        }
    }

    if ((stageIdx === 3 || stageIdx === 4) && (sets.generating || sets.reachable)) {
        if (sets.generating) {
            items.push({
                text: [
                    { text: 'Generating  G = ', bold: true, color: C.navy, fontSize: 9 },
                    { text: `{ ${sets.generating.join(', ') || 'empty'} }`, color: C.emeraldHex, fontSize: 9 }
                ],
                margin: [0, 1, 0, 1]
            });
        }
        if (sets.reachable) {
            items.push({
                text: [
                    { text: 'Reachable  R = ', bold: true, color: C.navy, fontSize: 9 },
                    { text: `{ ${sets.reachable.join(', ') || 'empty'} }`, color: C.blue, fontSize: 9 }
                ],
                margin: [0, 1, 0, 1]
            });
        }
    }

    return items;
}

// ─── Metrics delta row ─────────────────────────────────

function buildMetricsDelta(before, after) {
    const fmt = (b, a) => {
        const d = a - b;
        const sign = d > 0 ? '+' : '';
        const color = d < 0 ? C.emeraldHex : (d > 0 ? C.red : C.grayText);
        return { text: `${b} -> ${a}  (${sign}${d})`, color: color, fontSize: 8, noWrap: true };
    };

    return {
        table: {
            widths: ['*', '*', '*'],
            body: [
                [
                    { text: 'Productions', bold: true, fontSize: 7, color: C.white, fillColor: C.navy, alignment: 'center' },
                    { text: 'Variables', bold: true, fontSize: 7, color: C.white, fillColor: C.navy, alignment: 'center' },
                    { text: 'Terminals', bold: true, fontSize: 7, color: C.white, fillColor: C.navy, alignment: 'center' }
                ],
                [
                    { ...fmt(before.productions, after.productions), alignment: 'center' },
                    { ...fmt(before.variables, after.variables), alignment: 'center' },
                    { ...fmt(before.terminals, after.terminals), alignment: 'center' }
                ]
            ]
        },
        layout: {
            hLineWidth: () => 0.5,
            vLineWidth: () => 0.5,
            hLineColor: () => C.tableBorder,
            vLineColor: () => C.tableBorder,
            paddingTop: () => 3,
            paddingBottom: () => 3,
            paddingLeft: () => 4,
            paddingRight: () => 4
        },
        margin: [0, 3, 0, 0]
    };
}

// ─── Section header ────────────────────────────────────

function sectionHeader(text, stageNum) {
    return [
        {
            canvas: [
                { type: 'rect', x: 0, y: 0, w: 515, h: 24, r: 3, color: C.navy }
            ]
        },
        {
            text: [
                stageNum !== undefined
                    ? { text: `  ${stageNum}  `, bold: true, fontSize: 11, color: C.emeraldHex }
                    : { text: '' },
                { text: `  ${text}`, bold: true, fontSize: 11, color: C.white }
            ],
            margin: [6, -19, 0, 8]
        }
    ];
}

// ─── Build stage section ───────────────────────────────

function buildStageSection(stageIdx, stage, prevStage, domStages) {
    const stageNames = ['', 'Null Productions Removal', 'Unit Productions Removal', 'Useless Symbols Pruning', 'Validation & Convergence'];
    const content = [];

    // Header
    content.push(...sectionHeader(stageNames[stageIdx], stageIdx));

    // Description
    content.push({
        text: STAGE_DESCRIPTIONS[stageIdx],
        fontSize: 8,
        color: C.grayText,
        margin: [0, 0, 0, 4],
        lineHeight: 1.3
    });

    // Sets
    const setsContent = buildSetsContent(stage, stageIdx);
    if (setsContent.length > 0) {
        content.push({
            stack: [
                { text: 'Key Sets', bold: true, fontSize: 8, color: C.navy, margin: [0, 0, 0, 2] },
                ...setsContent
            ],
            margin: [0, 0, 0, 4],
        });
    }

    // Transformation log table
    const logRows = extractLogRows(stage);
    if (logRows.length > 0) {
        content.push({
            text: 'Transformation Log',
            bold: true, fontSize: 8, color: C.navy, margin: [0, 2, 0, 2]
        });

        content.push({
            table: {
                headerRows: 1,
                widths: [70, '*'],
                body: [
                    [
                        { text: 'Action', bold: true, fontSize: 7, fillColor: C.headerBg, color: C.white },
                        { text: 'Detail', bold: true, fontSize: 7, fillColor: C.headerBg, color: C.white }
                    ],
                    ...logRows.map((row, i) => row.map(cell => ({
                        ...cell,
                        fontSize: 7,
                        fillColor: i % 2 === 0 ? C.lightGray : C.white
                    })))
                ]
            },
            layout: {
                hLineWidth: (i, node) => (i === 0 || i === 1 || i === node.table.body.length) ? 0.6 : 0.2,
                vLineWidth: () => 0.2,
                hLineColor: (i) => i <= 1 ? C.emeraldHex : C.tableBorder,
                vLineColor: () => C.tableBorder,
                paddingTop: () => 2,
                paddingBottom: () => 2,
                paddingLeft: () => 4,
                paddingRight: () => 4
            },
            margin: [0, 0, 0, 6]
        });
    }

    // Graph capture
    if (domStages && domStages[stageIdx - 1]) {
        const imgData = captureNetworkCanvas(domStages[stageIdx - 1].network);
        if (imgData) {
            content.push({
                text: 'Dependency Graph',
                bold: true, fontSize: 8, color: C.navy, margin: [0, 2, 0, 2]
            });
            content.push({
                image: imgData,
                width: 400,
                alignment: 'center',
                margin: [0, 0, 0, 6]
            });
        }
    }

    // Before / After grammar side-by-side
    const beforeRows = grammarToTableBody(prevStage.grammar);
    const afterRows = grammarToTableBody(stage.grammar);
    const maxRows = Math.max(beforeRows.length, afterRows.length);

    if (maxRows > 0) {
        content.push({
            text: 'Grammar Comparison',
            bold: true, fontSize: 8, color: C.navy, margin: [0, 2, 0, 2]
        });

        while (beforeRows.length < maxRows) beforeRows.push([{ text: '' }, { text: '' }, { text: '' }]);
        while (afterRows.length < maxRows) afterRows.push([{ text: '' }, { text: '' }, { text: '' }]);

        content.push({
            columns: [
                {
                    width: '48%',
                    stack: [
                        { text: 'Before', bold: true, fontSize: 7, color: C.grayText, alignment: 'center', margin: [0, 0, 0, 2] },
                        {
                            table: { widths: ['auto', 18, '*'], body: beforeRows },
                            layout: {
                                hLineWidth: () => 0.2,
                                vLineWidth: () => 0,
                                hLineColor: () => C.tableBorder,
                                paddingTop: () => 1,
                                paddingBottom: () => 1,
                                paddingLeft: () => 3,
                                paddingRight: () => 3
                            }
                        }
                    ]
                },
                { width: '4%', text: '' },
                {
                    width: '48%',
                    stack: [
                        { text: 'After', bold: true, fontSize: 7, color: C.grayText, alignment: 'center', margin: [0, 0, 0, 2] },
                        {
                            table: { widths: ['auto', 18, '*'], body: afterRows },
                            layout: {
                                hLineWidth: () => 0.2,
                                vLineWidth: () => 0,
                                hLineColor: () => C.tableBorder,
                                paddingTop: () => 1,
                                paddingBottom: () => 1,
                                paddingLeft: () => 3,
                                paddingRight: () => 3
                            }
                        }
                    ]
                }
            ],
            margin: [0, 0, 0, 4]
        });
    }

    // Metrics delta
    content.push(buildMetricsDelta(prevStage.metrics, stage.metrics));

    // Separator line between stages instead of page break
    content.push({
        canvas: [
            { type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: C.tableBorder }
        ],
        margin: [0, 8, 0, 8]
    });

    return content;
}

// ─── Main export ───────────────────────────────────────

export function generateReport(pipelineHistory, stageLabels, networkInstances, domStages) {
    if (!pipelineHistory || pipelineHistory.length === 0) {
        alert('Please run the simplification first.');
        return;
    }

    const initial = pipelineHistory[0];
    const final = pipelineHistory[4];
    const dateStr = new Date().toLocaleString();

    const calcRed = (s, f) => s === 0 ? '0%' : `${Math.round((1 - f / s) * 100)}%`;

    // ─── Document Definition ───────────────────────────

    const dd = {
        pageSize: 'A4',
        pageMargins: [36, 45, 36, 40],

        // ── Header ─────────────────────────────────────
        header: (currentPage) => {
            if (currentPage === 1) return null;
            return {
                columns: [
                    {
                        text: 'CFG Simplification Report',
                        fontSize: 7,
                        color: C.grayText,
                        margin: [36, 16, 0, 0]
                    },
                    {
                        canvas: [
                            { type: 'line', x1: 0, y1: 0, x2: 80, y2: 0, lineWidth: 1.5, lineColor: C.emeraldHex }
                        ],
                        alignment: 'right',
                        margin: [0, 18, 36, 0]
                    }
                ]
            };
        },

        // ── Footer ─────────────────────────────────────
        footer: (currentPage, pageCount) => ({
            columns: [
                {
                    text: 'Generated by CFG Simplifier',
                    fontSize: 6,
                    color: C.grayText,
                    margin: [36, 0, 0, 0]
                },
                {
                    text: `Page ${currentPage} of ${pageCount}`,
                    alignment: 'right',
                    fontSize: 6,
                    color: C.grayText,
                    margin: [0, 0, 36, 0]
                }
            ],
            margin: [0, 10, 0, 0]
        }),

        // ── Content ────────────────────────────────────
        content: [
            // ═══════════ COVER PAGE ═══════════
            { text: '', margin: [0, 40, 0, 0] },

            // Accent bar
            {
                canvas: [
                    { type: 'rect', x: 0, y: 0, w: 515, h: 3, r: 1.5, color: C.emeraldHex }
                ],
                margin: [0, 0, 0, 10]
            },

            // Title
            {
                text: 'CFG Simplification Report',
                fontSize: 30,
                bold: true,
                color: C.navy,
                lineHeight: 1.1,
                margin: [0, 0, 0, 8]
            },

            // Subtitle
            {
                text: 'Complete Pipeline Execution Trace & Analysis',
                fontSize: 12,
                color: C.grayText,
                margin: [0, 0, 0, 15]
            },

            // Date & version
            {
                columns: [
                    {
                        width: 'auto',
                        text: [
                            { text: 'Generated: ', bold: true, fontSize: 8, color: C.navy },
                            { text: dateStr, fontSize: 8, color: C.grayText }
                        ]
                    },
                    {
                        width: 'auto',
                        text: [
                            { text: 'Engine: ', bold: true, fontSize: 8, color: C.navy },
                            { text: 'CFG Simplifier v2.0', fontSize: 8, color: C.grayText }
                        ],
                        margin: [20, 0, 0, 0]
                    }
                ],
                margin: [0, 0, 0, 12]
            },

            // Quick stats overview
            {
                canvas: [
                    { type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: C.tableBorder }
                ],
                margin: [0, 0, 0, 10]
            },

            {
                columns: [
                    {
                        width: '33%',
                        stack: [
                            { text: 'INITIAL', fontSize: 7, color: C.grayText, bold: true, margin: [0, 0, 0, 2] },
                            { text: `${initial.metrics.productions}`, fontSize: 24, bold: true, color: C.navy },
                            { text: 'Productions', fontSize: 8, color: C.grayText }
                        ],
                        alignment: 'center'
                    },
                    {
                        width: '34%',
                        stack: [
                            { text: 'FINAL', fontSize: 7, color: C.grayText, bold: true, margin: [0, 0, 0, 2] },
                            { text: `${final.metrics.productions}`, fontSize: 24, bold: true, color: C.emeraldHex },
                            { text: 'Productions', fontSize: 8, color: C.grayText }
                        ],
                        alignment: 'center'
                    },
                    {
                        width: '33%',
                        stack: [
                            { text: 'REDUCTION', fontSize: 7, color: C.grayText, bold: true, margin: [0, 0, 0, 2] },
                            { text: calcRed(initial.metrics.productions, final.metrics.productions), fontSize: 24, bold: true, color: C.red },
                            { text: 'Removed', fontSize: 8, color: C.grayText }
                        ],
                        alignment: 'center'
                    }
                ],
                margin: [0, 0, 0, 12]
            },

            {
                canvas: [
                    { type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: C.tableBorder }
                ],
                margin: [0, 0, 0, 10]
            },

            // Pipeline stages mini overview
            {
                text: 'Pipeline Stages',
                fontSize: 9,
                bold: true,
                color: C.navy,
                margin: [0, 0, 0, 4]
            },
            {
                table: {
                    widths: [25, '*', 50, 50],
                    body: [
                        [
                            { text: '#', bold: true, fontSize: 7, fillColor: C.navy, color: C.white, alignment: 'center' },
                            { text: 'Stage', bold: true, fontSize: 7, fillColor: C.navy, color: C.white },
                            { text: 'Before', bold: true, fontSize: 7, fillColor: C.navy, color: C.white, alignment: 'center' },
                            { text: 'After', bold: true, fontSize: 7, fillColor: C.navy, color: C.white, alignment: 'center' }
                        ],
                        ...([1, 2, 3, 4].map(i => [
                            { text: `${i}`, fontSize: 7, alignment: 'center', color: C.emeraldHex, bold: true, fillColor: i % 2 === 0 ? C.lightGray : C.white },
                            { text: stageLabels[i], fontSize: 7, color: C.darkText, fillColor: i % 2 === 0 ? C.lightGray : C.white },
                            { text: `${pipelineHistory[i - 1].metrics.productions}`, fontSize: 7, alignment: 'center', color: C.grayText, fillColor: i % 2 === 0 ? C.lightGray : C.white },
                            { text: `${pipelineHistory[i].metrics.productions}`, fontSize: 7, alignment: 'center', color: C.darkText, bold: true, fillColor: i % 2 === 0 ? C.lightGray : C.white }
                        ]))
                    ]
                },
                layout: {
                    hLineWidth: (i, node) => (i === 0 || i === 1 || i === node.table.body.length) ? 0.6 : 0.2,
                    vLineWidth: () => 0.2,
                    hLineColor: (i) => i <= 1 ? C.navy : C.tableBorder,
                    vLineColor: () => C.tableBorder,
                    paddingTop: () => 3,
                    paddingBottom: () => 3,
                    paddingLeft: () => 4,
                    paddingRight: () => 4
                },
                margin: [0, 0, 0, 12]
            },

            // ═══════════ INPUT GRAMMAR (same page as cover) ═══════════
            ...sectionHeader('Input Grammar', 0),

            {
                text: 'The original grammar as provided by the user, before any simplification.',
                fontSize: 8,
                color: C.grayText,
                margin: [0, 0, 0, 4],
                lineHeight: 1.3
            },

            // Grammar rules + metrics side by side
            {
                columns: [
                    {
                        width: '60%',
                        stack: [
                            { text: 'Grammar Rules', bold: true, fontSize: 8, color: C.navy, margin: [0, 0, 0, 2] },
                            {
                                table: { widths: ['auto', 18, '*'], body: grammarToTableBody(initial.grammar) },
                                layout: {
                                    hLineWidth: () => 0.2,
                                    vLineWidth: () => 0,
                                    hLineColor: () => C.tableBorder,
                                    paddingTop: () => 2,
                                    paddingBottom: () => 2,
                                    paddingLeft: () => 6,
                                    paddingRight: () => 6
                                }
                            }
                        ]
                    },
                    { width: '5%', text: '' },
                    {
                        width: '35%',
                        stack: [
                            { text: 'Initial Metrics', bold: true, fontSize: 8, color: C.navy, margin: [0, 0, 0, 2] },
                            {
                                table: {
                                    widths: ['*', 'auto'],
                                    body: [
                                        [
                                            { text: 'Productions', fontSize: 8, color: C.grayText },
                                            { text: `${initial.metrics.productions}`, fontSize: 10, bold: true, color: C.navy, alignment: 'center' }
                                        ],
                                        [
                                            { text: 'Variables', fontSize: 8, color: C.grayText, fillColor: C.lightGray },
                                            { text: `${initial.metrics.variables}`, fontSize: 10, bold: true, color: C.navy, alignment: 'center', fillColor: C.lightGray }
                                        ],
                                        [
                                            { text: 'Terminals', fontSize: 8, color: C.grayText },
                                            { text: `${initial.metrics.terminals}`, fontSize: 10, bold: true, color: C.navy, alignment: 'center' }
                                        ]
                                    ]
                                },
                                layout: {
                                    hLineWidth: () => 0.3,
                                    vLineWidth: () => 0.3,
                                    hLineColor: () => C.tableBorder,
                                    vLineColor: () => C.tableBorder,
                                    paddingTop: () => 3,
                                    paddingBottom: () => 3,
                                    paddingLeft: () => 5,
                                    paddingRight: () => 5
                                }
                            }
                        ]
                    }
                ],
                margin: [0, 0, 0, 0]
            },

            // Page break before stages
            { text: '', pageBreak: 'after' },

            // ═══════════ STAGE SECTIONS 1-4 (continuous flow) ═══════════
            ...buildStageSection(1, pipelineHistory[1], pipelineHistory[0], domStages),
            ...buildStageSection(2, pipelineHistory[2], pipelineHistory[1], domStages),
            ...buildStageSection(3, pipelineHistory[3], pipelineHistory[2], domStages),
            ...buildStageSection(4, pipelineHistory[4], pipelineHistory[3], domStages),

            // ═══════════ FINAL RESULT ═══════════
            ...sectionHeader('Final Simplified Grammar'),

            {
                text: 'The fully simplified, equivalent context-free grammar after all pipeline stages.',
                fontSize: 8,
                color: C.grayText,
                margin: [0, 0, 0, 6],
                lineHeight: 1.3
            },

            // Validation banner
            (() => {
                const validationLog = (pipelineHistory[4].step_logs || pipelineHistory[4].logs || []);
                const isStable = validationLog.some(l => l.type === 'summary-clear');
                return {
                    table: {
                        widths: ['*'],
                        body: [[{
                            text: isStable
                                ? 'VALIDATION PASSED -- Grammar is mathematically stable and minimal'
                                : 'VALIDATION WARNING -- Grammar may require additional passes',
                            bold: true,
                            fontSize: 9,
                            color: isStable ? '#065f46' : '#991b1b',
                            fillColor: isStable ? C.greenBg : C.redBg,
                            alignment: 'center'
                        }]]
                    },
                    layout: {
                        hLineWidth: () => 0.8,
                        vLineWidth: () => 0.8,
                        hLineColor: () => isStable ? C.emeraldHex : C.red,
                        vLineColor: () => isStable ? C.emeraldHex : C.red,
                        paddingTop: () => 6,
                        paddingBottom: () => 6,
                        paddingLeft: () => 8,
                        paddingRight: () => 8
                    },
                    margin: [0, 0, 0, 8]
                };
            })(),

            // Final grammar + reduction summary side by side
            {
                columns: [
                    {
                        width: '50%',
                        stack: [
                            { text: 'Final Grammar', bold: true, fontSize: 8, color: C.navy, margin: [0, 0, 0, 2] },
                            {
                                table: { widths: ['auto', 18, '*'], body: grammarToTableBody(final.grammar) },
                                layout: {
                                    hLineWidth: () => 0.2,
                                    vLineWidth: () => 0,
                                    hLineColor: () => C.tableBorder,
                                    paddingTop: () => 2,
                                    paddingBottom: () => 2,
                                    paddingLeft: () => 6,
                                    paddingRight: () => 6
                                }
                            }
                        ]
                    },
                    { width: '5%', text: '' },
                    {
                        width: '45%',
                        stack: [
                            { text: 'Reduction Summary', bold: true, fontSize: 8, color: C.navy, margin: [0, 0, 0, 2] },
                            {
                                table: {
                                    headerRows: 1,
                                    widths: ['*', 45, 45, 50],
                                    body: [
                                        [
                                            { text: 'Metric', bold: true, fontSize: 7, fillColor: C.headerBg, color: C.white },
                                            { text: 'Start', bold: true, fontSize: 7, fillColor: C.headerBg, color: C.white, alignment: 'center' },
                                            { text: 'Final', bold: true, fontSize: 7, fillColor: C.headerBg, color: C.white, alignment: 'center' },
                                            { text: 'Reduced', bold: true, fontSize: 7, fillColor: C.headerBg, color: C.white, alignment: 'center' }
                                        ],
                                        [
                                            { text: 'Productions', fontSize: 7, color: C.darkText },
                                            { text: `${initial.metrics.productions}`, fontSize: 7, alignment: 'center', color: C.grayText },
                                            { text: `${final.metrics.productions}`, fontSize: 7, alignment: 'center', color: C.navy, bold: true },
                                            { text: calcRed(initial.metrics.productions, final.metrics.productions), fontSize: 7, alignment: 'center', color: C.red, bold: true }
                                        ],
                                        [
                                            { text: 'Variables', fontSize: 7, color: C.darkText, fillColor: C.lightGray },
                                            { text: `${initial.metrics.variables}`, fontSize: 7, alignment: 'center', color: C.grayText, fillColor: C.lightGray },
                                            { text: `${final.metrics.variables}`, fontSize: 7, alignment: 'center', color: C.navy, bold: true, fillColor: C.lightGray },
                                            { text: calcRed(initial.metrics.variables, final.metrics.variables), fontSize: 7, alignment: 'center', color: C.red, bold: true, fillColor: C.lightGray }
                                        ],
                                        [
                                            { text: 'Terminals', fontSize: 7, color: C.darkText },
                                            { text: `${initial.metrics.terminals}`, fontSize: 7, alignment: 'center', color: C.grayText },
                                            { text: `${final.metrics.terminals}`, fontSize: 7, alignment: 'center', color: C.navy, bold: true },
                                            { text: calcRed(initial.metrics.terminals, final.metrics.terminals), fontSize: 7, alignment: 'center', color: C.red, bold: true }
                                        ]
                                    ]
                                },
                                layout: {
                                    hLineWidth: (i, node) => (i === 0 || i === 1 || i === node.table.body.length) ? 0.6 : 0.2,
                                    vLineWidth: () => 0.2,
                                    hLineColor: (i) => i <= 1 ? C.emeraldHex : C.tableBorder,
                                    vLineColor: () => C.tableBorder,
                                    paddingTop: () => 3,
                                    paddingBottom: () => 3,
                                    paddingLeft: () => 4,
                                    paddingRight: () => 4
                                }
                            }
                        ]
                    }
                ],
                margin: [0, 0, 0, 12]
            },

            // Closing accent bar
            {
                canvas: [
                    { type: 'rect', x: 0, y: 0, w: 515, h: 2, r: 1, color: C.emeraldHex }
                ],
                margin: [0, 5, 0, 4]
            },
            {
                text: `Report complete - ${dateStr}`,
                fontSize: 7,
                color: C.grayText,
                alignment: 'center'
            }
        ],

        // ── Default styles ─────────────────────────────
        defaultStyle: {
            font: 'Roboto'
        }
    };

    // ── Generate ───────────────────────────────────────
    pdfMake.createPdf(dd).download(`CFG_Report_${Date.now()}.pdf`);
}
